### ISSUE TITLE
MVPレビュー依頼

### ISSUE THREAD

**Issue by Yamachan-r** [Yamachan-r/Tsunagi_memo#48]
いつもお世話になっております。
MVPリリースに向けて、レビューのご依頼です。
README提出時点のものからの変更が多くなっております。
申し訳ございませんが、ご確認のほどよろしくお願いします。
___

## 各種情報
サービスの概要とMVPで検証する事柄：
家族間で医療や介護の情報を共有するアプリです。自身の基本情報や医療機関での説明などを記録し、遠方の家族とも簡単に情報を共有できることを目的としています。

メイン機能は、自身で登録した基本情報や病歴が、家族間で共有できることです。
※MVP時点では、アカウントログインできる（=自身で情報を登録できる）ユーザーへ絞り込んで実装しています。

サービス名：つなぎメモ
サービスURL：https://tsunagi-memo.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] トップページ
- [x] LINEログイン機能（会員登録、ログイン）
- [x] グループ作成機能
- [x] 家族メンバーの招待機能
- [x] ユーザー情報の登録機能（基本情報、病歴）
- [x] 登録情報の詳細画面（基本情報、病歴）
- [x] 登録情報の編集機能（基本情報、病歴）
- [x] 登録情報の一覧表示機能（病歴）
- [x] 登録情報の削除機能（病歴）

【READMEレビュー時にMVPリリース時点で実装予定だったが、MVP後へ変更した機能（次項目に詳細記載）】
- [ ] グループに所属するメンバーを削除する機能
- [ ] アカウント作成できないメンバー（子どもや高齢者）を登録する機能
- [ ] アカウント作成できないメンバー（子どもや高齢者）を編集する機能

### 以下の項目は、本リリース時に実装予定する方向へ変更いたしました。
理由としては、卒業が年末年始と時期が被ってしまいレビューに時間がかかってしまう可能性を考慮し、期間に余裕を持ってMVPリリースすることを目標にしたためです。
- **アカウント作成できないメンバー（子どもや高齢者）を登録・編集する機能**
- **グループに所属するメンバーを削除する機能**
アカウント作成しているユーザーのみが家族グループに属し共有できているという点で、最低限のメイン機能（家族間での情報共有をすること）を満たしていると判断し、変更いたしました。
- **登録できる情報の項目の絞り込み**
READMEには登録できる情報の例として複数個載せていたのですが、登録項目は最低限必要な項目に絞って実装しております。MVP後、登録できる項目を増やしていきたいと考えております。
- **スマホに合わせたCSS関連、ヘッダー等の追加**
スマホでの使用がメインとなることを考えて、スマホ画面での画面遷移やデザインを作成しておりました。ですが、MVP時点では最低限のメイン機能を実装ということで、画面遷移についてやデザインは現時点では仮作成にしております。

## サービスイメージがわかるようなスクリーンショット等
通常ユーザーが触れない機能や画面はありません。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
